from pathlib import Path
import json,re,xml.etree.ElementTree as ET

ROOT=Path('suncoast-site')
DATE='2026-09-07'
PHONE='(561) 956-8866'
BASE='https://suncoastcapitalmortgage.com'

def page(title,desc,slug,h1,lead,body,faqs):
    schema={"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{"@type":"Question","name":q,"acceptedAnswer":{"@type":"Answer","text":a}} for q,a in faqs]}
    return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title}</title><meta name="description" content="{desc}"><link rel="canonical" href="{BASE}/{slug}"><meta name="robots" content="index,follow,max-image-preview:large"><meta property="og:type" content="website"><meta property="og:title" content="{title}"><meta property="og:description" content="{desc}"><meta property="og:url" content="{BASE}/{slug}"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@600;700&family=Outfit:wght@300;400;500;600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="/county.css"><script defer src="/tracking.js?v=20260904-2"></script><script type="application/ld+json">{json.dumps(schema,separators=(',',':'))}</script></head><body>
<div class="topbar">Florida mortgage inquiries · <a href="tel:15619568866">{PHONE}</a> · Mortgage services provided by West Coast Capital Mortgage Inc. where licensed</div><nav class="nav"><div class="nav-inner"><a class="brand" href="/"><span class="brand-mark" aria-hidden="true"></span><span><strong>Suncoast Capital</strong><span>Mortgage · Florida</span></span></a><div class="nav-links"><a href="/#markets">South Florida</a><a href="/#programs">Programs</a><a href="/investment-property-loans">Investor</a><a href="/jumbo-loans">Jumbo</a></div><a class="nav-phone" href="tel:15619568866">Call Florida Desk</a></div></nav>
<header class="hero"><div class="shell"><p class="eyebrow">Updated September 2026</p><h1>{h1}</h1><p class="lede">{lead}</p><div class="button-row"><a class="button button-primary" href="/#review">Send My Scenario</a><a class="button button-secondary" data-application-start href="https://westcoastcapitalmortgage.com/apply">Start an Application</a></div><p class="hero-note">Eligibility, pricing, documentation and property requirements vary by borrower, property, program and lender. This page is educational and is not a commitment to lend.</p></div></header>{body}
<section class="section section-sky"><div class="shell"><p class="eyebrow">Compare before choosing</p><h2>A borrower arriving with one assumed solution may have other financing paths.</h2><div class="button-row"><a class="button button-primary" href="/investment-property-loans">Investor Options</a><a class="button button-secondary" href="/dscr-loans">DSCR</a><a class="button button-secondary" href="/self-employed-borrowers">Self-Employed</a><a class="button button-secondary" href="/jumbo-loans">Jumbo</a></div></div></section>
<footer class="footer"><div class="footer-grid"><div><strong>Suncoast Capital Mortgage</strong><p>Florida-facing mortgage education and scenario review. Mortgage services are provided by West Coast Capital Mortgage Inc. where licensed.</p><p><strong>West Coast Capital Mortgage Inc.</strong><br>150 E Olive Ave, Unit 112, Burbank, CA 91502<br>(310) 654-1577 · Company NMLS #2817729 · CA DRE Corporation License #02440065</p></div><div><strong>Florida financing</strong><ul><li><a href="/investment-property-loans">Investment Property</a></li><li><a href="/dscr-loans">DSCR</a></li><li><a href="/self-employed-borrowers">Self-Employed</a></li><li><a href="/jumbo-loans">Jumbo</a></li></ul></div><div><strong>Florida desks</strong><ul><li><a href="/miami-dade-county-mortgage">Miami-Dade</a></li><li><a href="/broward-county-mortgage">Broward</a></li><li><a href="/palm-beach-county-mortgage">Palm Beach</a></li></ul><span class="eho"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 11.5 12 4l9 7.5v8.5H3z"/><path d="M8 13h8M8 16h8"/></svg>Equal Housing Opportunity</span></div></div><div class="footer-bottom">Information is for general educational and scenario-review purposes only and is not a commitment to lend. Programs, terms and eligibility vary by lender and borrower/property profile. © 2026 Suncoast Capital Mortgage.</div></footer></body></html>'''

invest_faq=[('Can short-term rental income be used to qualify?','Potentially, in eligible scenarios. Conventional Agency, DSCR and Non-QM programs evaluate short-term-rental income differently. Eligibility depends on the borrower, property, legal rental use, documentation and current Agency or lender guidelines.'),('When can conventional financing work for a Florida rental property?','Conventional financing may work when borrower, property, occupancy, rental-income history and required documentation meet current Agency and lender requirements.'),('When may DSCR be a better option?','DSCR may be worth comparing when investment-property cash flow provides the primary qualification path. Program terms and documentation vary.'),('What documentation may be required?','Depending on the scenario, documentation can include leases, tax-return or Schedule E history, market-rent analysis, current housing-payment evidence, proof of legal short-term-rental use, assets, reserves or program-specific documents.')]
invest_body='''<section class="section" id="comparison"><div class="shell"><h2>Florida Investment Property Loans: Conventional vs. DSCR vs. Non-QM</h2><p><strong>Direct answer:</strong> A Florida rental property does not automatically require DSCR or Non-QM. Some investors may have a conventional Agency path; DSCR or another Non-QM structure may fit other scenarios. The comparison depends on borrower profile, property type, rental history, documentation and current guidelines.</p><div class="grid-3"><article class="card"><h3>Conventional</h3><p>Agency rental-income rules may work when borrower, property and documentation requirements are satisfied.</p></article><article class="card"><h3>DSCR</h3><p>Investment-property financing focused primarily on property cash flow rather than traditional employment income.</p></article><article class="card"><h3>Non-QM</h3><p>Alternative documentation or property structures may be available when an Agency execution is not the best fit.</p></article></div><h2>What about short-term rentals and Florida condos?</h2><p><strong>Direct answer:</strong> Both require scenario-specific review. Short-term-rental income treatment differs by program, and condo project eligibility, insurance, reserves, structural information and lender overlays may affect financing independently of the borrower.</p><p><strong>Have a Florida rental property, condo or short-term rental?</strong> We can compare Conventional, DSCR and Non-QM options before you choose a loan.</p></div></section>'''

(ROOT/'investment-property-loans.html').write_text(page('Florida Investment Property Loans: Conventional vs DSCR vs Non-QM | Suncoast Capital Mortgage','Compare Florida investment property financing: Conventional Agency, DSCR and Non-QM options for rentals, condos and eligible short-term-rental scenarios.','investment-property-loans','Florida Investment Property Loans: Conventional vs. DSCR vs. Non-QM','Compare the financing structure before assuming a rental property needs one specific investor loan.',invest_body,invest_faq))

dscr_faq=[('Does every Florida rental property need a DSCR loan?','No. Some investors may also have a conventional Agency option. The appropriate path depends on borrower, property, rental-income documentation and current program requirements.'),('Can a Florida short-term rental use conventional financing?','In some eligible scenarios, short-term-rental income may be considered under current Agency guidance, subject to property eligibility, legal use, rental history, documentation and lender requirements.')]
dscr_body='''<section class="section"><div class="shell"><h2>Does Every Florida Rental Property Need a DSCR Loan?</h2><p><strong>Direct answer:</strong> No. Some rental-property borrowers may have a conventional Agency option, while others may be better served by DSCR or another Non-QM structure. We compare the borrower, property, rental-income documentation and current program rules rather than assuming one loan type.</p><div class="grid-3"><article class="card"><h3>Conventional</h3><p>Potential fit when Agency borrower, property and rental-income requirements can be met.</p></article><article class="card"><h3>DSCR</h3><p>Potential fit when investment-property cash flow is the primary qualification path.</p></article><article class="card"><h3>Other Non-QM</h3><p>Potential fit for alternative documentation or scenarios outside standard Agency guidelines.</p></article></div><h2>Can a short-term rental use conventional financing?</h2><p><strong>Direct answer:</strong> In some eligible scenarios, short-term-rental income may be considered under current Agency guidance. Legal STR use, property eligibility, rental history, appraisal or rent documentation and lender requirements matter. This is scenario analysis, not a qualification promise.</p></div></section>'''
(ROOT/'dscr-loans.html').write_text(page('Florida DSCR Loans: Compare DSCR vs Conventional | Suncoast Capital Mortgage','Florida DSCR financing for investment properties, with a direct comparison to conventional Agency and other Non-QM paths.','dscr-loans','Florida DSCR Loans: Compare the Property-Cash-Flow Path','DSCR can be useful for investors, but it should not be assumed to be the only rental-property financing option.',dscr_body,dscr_faq))

self_faq=[('Can I get a mortgage if my tax returns show low income?','Possibly. Depending on the borrower and property, traditional Agency analysis, bank statements, asset-based or asset-utilization programs, or DSCR for an investment property may be worth comparing.'),('Can bank statements be used instead of tax returns?','Some Non-QM bank-statement programs can evaluate eligible deposits rather than relying solely on tax-return income. Documentation and expense treatment vary by program.'),('Can assets be used to qualify for a mortgage?','Some programs may use eligible assets or an asset-utilization calculation. Asset treatment, reserves and documentation vary by program.'),('What mortgage options exist for a self-employed real estate investor?','Potential paths can include traditional Agency documentation, bank-statement programs, asset-based or asset-utilization programs, DSCR and other Non-QM structures.')]
self_body='''<section class="section"><div class="shell"><h2>Which Mortgage Qualification Method Can Work for a Self-Employed Florida Borrower?</h2><p><strong>Direct answer:</strong> Self-employed does not automatically mean Non-QM. Compare traditional income documentation, bank-statement qualification, asset-based or asset-utilization approaches, and DSCR for an eligible investment property before selecting a structure.</p><div class="grid-4"><article class="card"><h3>Traditional Income Documentation</h3><p>Agency or traditional underwriting may work when tax returns and applicable income analysis support the loan.</p></article><article class="card"><h3>Bank Statement</h3><p>Some Non-QM programs analyze eligible deposits and business-expense factors rather than taxable net income alone.</p></article><article class="card"><h3>Asset-Based / Asset Utilization</h3><p>Some programs can evaluate eligible assets using program-specific calculations and reserve rules.</p></article><article class="card"><h3>DSCR for Investment Property</h3><p>For eligible investment properties, DSCR may focus primarily on property cash flow rather than employment income.</p></article></div></div></section>'''
(ROOT/'self-employed-borrowers.html').write_text(page('Self-Employed Mortgage Options in Florida | Suncoast Capital Mortgage','Compare Florida mortgage qualification paths for self-employed borrowers: traditional documentation, bank statements, assets and DSCR for investment property.','self-employed-borrowers','Self-Employed Mortgage Options in Florida','Do not assume that self-employment automatically requires a Non-QM loan. Compare the available qualification methods first.',self_body,self_faq))

jumbo_faq=[('Should a South Florida buyer compare jumbo with other financing structures?','Yes. Depending on loan amount and borrower profile, compare jumbo, applicable conforming or high-balance options, traditional documentation, bank-statement and asset-based paths before selecting a structure.'),('Is jumbo always more expensive than high-balance financing?','No permanent pricing assumption should be made. Current execution varies with market pricing, borrower profile, reserves, documentation, property and program requirements.')]
jumbo_body='''<section class="section"><div class="shell"><h2>High-Balance vs. Jumbo Loan Comparison</h2><p><strong>Direct answer:</strong> High-balance conforming and jumbo loans are different executions. Where a high-cost conforming option applies, a borrower may still benefit from comparing current jumbo structures. The fit depends on loan amount, current pricing, credit, reserves, income documentation, property and underwriting.</p><div class="grid-2"><article class="card"><h3>High-Balance Conforming</h3><p>Follows applicable Agency high-cost limits and underwriting requirements where available.</p></article><article class="card"><h3>Jumbo</h3><p>Non-conforming financing with lender-specific reserve, documentation and property requirements.</p></article></div><h2>South Florida Luxury Financing</h2><p><strong>Direct answer:</strong> Buyers in Miami, Palm Beach and other South Florida luxury markets may benefit from comparing jumbo, traditional documentation, bank-statement and asset-based qualification paths before making an offer. Strong financing readiness can reduce uncertainty, while final approval remains subject to complete underwriting and property review.</p><p><strong>Before choosing a high-balance loan, compare it with current jumbo options.</strong></p></div></section>'''
(ROOT/'jumbo-loans.html').write_text(page('Jumbo Loans in South Florida: High-Balance vs Jumbo | Suncoast Capital Mortgage','Compare South Florida jumbo and high-balance financing, including options for self-employed and asset-rich luxury buyers in Miami and Palm Beach.','jumbo-loans','South Florida Jumbo Financing: Compare the Structure Before the Offer','For luxury and high-value Florida purchases, loan size is only one part of the financing decision.',jumbo_body,jumbo_faq))

# Homepage: add strong entry points and make existing program cards clickable.
home=ROOT/'index.html'; s=home.read_text()
if 'SEP2026-AEO:florida-entry-points' not in s:
    block='''\n<!-- SEP2026-AEO:florida-entry-points -->\n<section class="section section-ivory"><div class="shell"><div class="section-head"><div><p class="eyebrow">Updated September 2026</p><h2>Two Florida financing paths worth comparing early.</h2></div><p>South Florida luxury and Florida investment-property financing often require different documentation, property review and underwriting strategies.</p></div><div class="grid-2"><article class="card"><span class="tag">South Florida luxury</span><h3>Jumbo, self-employed and asset-based qualification</h3><p>For Miami, Palm Beach and other high-value Florida purchases, compare jumbo execution with the borrower’s strongest documentation path before making an offer.</p><a class="text-link" href="/jumbo-loans">Compare South Florida jumbo options →</a></article><article class="card"><span class="tag">Florida investment property</span><h3>Conventional vs. DSCR vs. Non-QM</h3><p>For rentals, condos and eligible short-term-rental scenarios, compare Agency rental-income rules with DSCR and other Non-QM structures.</p><a class="text-link" href="/investment-property-loans">Compare investor financing →</a></article></div></div></section>\n'''
    marker='<section class="section section-navy">'
    s=s.replace(marker,block+marker,1)
# Link the four existing program cards.
s=s.replace('<h3>Jumbo &amp; High-Value</h3><p>Large loan amounts, complex assets, liquidity and high-value Florida property.</p>','<h3>Jumbo &amp; High-Value</h3><p>Large loan amounts, complex assets, liquidity and high-value Florida property.</p><a class="text-link" href="/jumbo-loans">Compare jumbo structures →</a>')
s=s.replace('<h3>DSCR &amp; Investor</h3><p>Rental-property scenarios where property cash flow may be part of the lender review.</p>','<h3>DSCR &amp; Investor</h3><p>Rental-property scenarios where property cash flow may be part of the lender review.</p><a class="text-link" href="/investment-property-loans">Compare investor paths →</a>')
s=s.replace('<h3>Self-Employed</h3><p>Bank-statement and other alternative-documentation paths when traditional income documentation does not tell the whole story.</p>','<h3>Self-Employed</h3><p>Bank-statement and other alternative-documentation paths when traditional income documentation does not tell the whole story.</p><a class="text-link" href="/self-employed-borrowers">Compare qualification methods →</a>')
home.write_text(s)

# Sitemap: preserve existing URLs, add/refresh only affected pages.
sm=ROOT/'sitemap.xml'; text=sm.read_text()
urls=['/','/investment-property-loans','/dscr-loans','/self-employed-borrowers','/jumbo-loans']
for path in urls:
    u=BASE+path
    if u in text:
        text=re.sub(r'(<loc>'+re.escape(u)+r'</loc>\s*)(?:<lastmod>[^<]+</lastmod>)?',lambda m:m.group(1)+f'<lastmod>{DATE}</lastmod>',text,count=1)
    else:
        text=text.replace('</urlset>',f'<url><loc>{u}</loc><lastmod>{DATE}</lastmod><changefreq>monthly</changefreq><priority>{"1.0" if path=="/" else "0.9"}</priority></url>\n</urlset>',1)
sm.write_text(text)

# Validation
for name in ['index.html','investment-property-loans.html','dscr-loans.html','self-employed-borrowers.html','jumbo-loans.html']:
    t=(ROOT/name).read_text(); assert t.count('<link rel="canonical"')==1,name
    assert 'guaranteed approval' not in t.lower(); assert 'lowest rate' not in t.lower(); assert 'fannie now finances airbnb' not in t.lower()
    for m in re.finditer(r'<script type="application/ld\+json">(.*?)</script>',t,re.S): json.loads(m.group(1))
ET.parse(sm)
print('Suncoast live Sep 2026 update: PASS')
